### ISSUE TITLE
Compatibility with MacOS (Apple Silicon)?

### ISSUE THREAD

**Issue by hoonsubin** [jellypower/JPSPathFindingForUnity#1]
Hey there! I love your package.

We're trying to build our game for MacOS, but I get this error when the game loads on a mac

```
DllNotFoundException: JPSPathfinderFaster assembly:<unknown assembly> type:<unknown type> member:(null)
DSNavigation.JPSPathFinderFaster.FindPath_UnsafeInternal (DSNavigation.JPSGridInfoToFindPath& GridInfo, DSNavigation.PathfinderPriorityQueuePool& priorityQueueSafe, DSNavigation.PathfinderCloseListPool& closeListSafe, UnityEngine.Vector2Int& Start, UnityEngine.Vector2Int& End, UnityEngine.Vector2Int[]& OutPath, System.UInt32& OutPathSize) (at Assets/Plugins/JPSPathFinderFaster/JPSPathFinderFaster.cs:242)
DSNavigation.JPSPathFinderFaster.FindPath (DSNavigation.JPSGridInfoFaster& jpsGrid, UnityEngine.Vector2& start, UnityEngine.Vector2& end, System.Collections.Generic.LinkedList`1[UnityEngine.Vector2]& outShortestPath) (at Assets/Plugins/JPSPathFinderFaster/JPSPathFinderFaster.cs:126)
CatchIo.Runtime.Agent.Core.AgentPathFinder.Update () (at Assets/Scripts/Runtime/Agent/Core/AgentPathFinder.cs:100)
```

![image](https://github.com/user-attachments/assets/70221584-92f3-4b6b-acd3-2f4e3389112a)

The plugin setting also doesn't seem to show Mac. Is there a way to make it support mac?

I've noticed similar issues on other packages:
- https://discussions.unity.com/t/why-do-i-get-a-dllnotfoundexception/214294/3
- https://discussions.unity.com/t/vivox-dllnotfoundexception-error-on-macbook-with-apple-silicon/892733
- https://github.com/firebase/quickstart-unity/issues/1308

**Comment by jellypower** [comment]
Thank you for your interest and Sorry for late reply.
Unfortunately, The project is based on Windows's visual studio and DLL is Windows based system so this project cannot run on iOS projects.
There are plans to port the project to Apple, but it has not been carried out yet due to lack of space.
Sorry for not being of help.
